// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

//! The rendered reviewer view of a catalog revision (design §7): every
//! effective policy, by entry, version option, platform, architecture, and
//! intent, so reviewers see what each combination actually grants.

use crate::catalog::{entry_index, CatalogContract, CatalogRevision};
use crate::effective::{materialize_entry, Materialized};
use crate::errors::Result;
use crate::json::{cmp_utf16, Json};
use crate::model::{Architecture, FilesystemPolicy, Platform};

fn cell(values: &[String]) -> String {
    if values.is_empty() {
        "—".to_string()
    } else {
        values
            .iter()
            .map(|v| format!("`{v}`"))
            .collect::<Vec<_>>()
            .join("<br>")
    }
}

fn paths(m: &Materialized, field: fn(&FilesystemPolicy) -> &Option<Vec<String>>) -> Vec<String> {
    m.policy
        .filesystem
        .as_ref()
        .and_then(|fs| field(fs).clone())
        .unwrap_or_default()
}

fn describe_rule(rule: &Json) -> String {
    let peers: Vec<String> = rule
        .get("to")
        .and_then(Json::as_array)
        .into_iter()
        .flatten()
        .map(|peer| {
            let cidr = peer.get("cidr").and_then(Json::as_str).unwrap_or("?");
            let except: Vec<&str> = peer
                .get("except")
                .and_then(Json::as_array)
                .into_iter()
                .flatten()
                .filter_map(Json::as_str)
                .collect();
            if except.is_empty() {
                cidr.to_string()
            } else {
                format!("{cidr} except {}", except.join(","))
            }
        })
        .collect();
    let ports: Vec<String> = rule
        .get("ports")
        .and_then(Json::as_array)
        .into_iter()
        .flatten()
        .map(|port| {
            let protocol = port.get("protocol").and_then(Json::as_str).unwrap_or("any");
            let number = |key| port.get(key).and_then(Json::as_f64).map(|n| n.to_string());
            match (number("port"), number("endPort")) {
                (Some(start), Some(end)) => format!("{protocol}/{start}-{end}"),
                (Some(start), None) => format!("{protocol}/{start}"),
                _ => protocol.to_string(),
            }
        })
        .collect();
    let peers = if peers.is_empty() {
        "*".to_string()
    } else {
        peers.join("+")
    };
    if ports.is_empty() {
        format!("{peers} any port")
    } else {
        format!("{peers} {}", ports.join("+"))
    }
}

fn egress(m: &Materialized) -> Vec<String> {
    let Some(network) = &m.policy.network else {
        return Vec::new();
    };
    let allow: Vec<String> = network
        .get("egress")
        .and_then(|e| e.get("allow"))
        .and_then(Json::as_array)
        .into_iter()
        .flatten()
        .map(describe_rule)
        .collect();
    if allow.is_empty() {
        vec![format!("{network}")]
    } else {
        allow
    }
}

fn row_cells(m: &Materialized) -> [String; 5] {
    [
        cell(&paths(m, |f| &f.readonly_paths)),
        cell(&paths(m, |f| &f.readwrite_paths)),
        cell(&paths(m, |f| &f.denied_paths)),
        cell(&egress(m)),
        cell(&m.dependency_entry_ids),
    ]
}

/// Renders the reviewer view (Markdown). Architectures with identical rows
/// collapse into one `any` row.
pub fn render_reviewer_view(
    revision: &CatalogRevision,
    contract: &CatalogContract,
) -> Result<String> {
    let by_id = entry_index(&revision.entries);
    let mut entries: Vec<_> = revision.entries.iter().collect();
    entries.sort_by(|a, b| cmp_utf16(&a.entry_id, &b.entry_id));
    let mut out = String::new();
    out.push_str(&format!(
        "<!-- Generated by mxc_policy_store::tooling::render_reviewer_view. Do not edit. -->\n\n# Catalog revision {} — reviewer view\n\nEvery effective policy each entry can produce: the default, plus platform additions, at most one version variant, and the selected intent. `(all)` means no intent was requested. Paths are unsubstituted templates.\n",
        revision.catalog_revision
    ));
    for entry in entries {
        let materialized = materialize_entry(entry, &by_id, contract)?;
        out.push_str(&format!(
            "\n## `{}` — {} (revision {}, `{}` versions)\n",
            entry.entry_id,
            entry.display_name,
            crate::catalog::revision_number(entry.entry_revision),
            entry.version_scheme
        ));
        let mut options: Vec<Option<String>> = vec![None];
        options.extend(
            entry
                .version_variants
                .iter()
                .map(|v| Some(v.version_range.as_str().to_string())),
        );
        for option in options {
            out.push_str(&format!(
                "\n### {}\n\n| Platform | Arch | Intent | Read-only | Read-write | Denied | Outbound allow | Dependencies |\n|---|---|---|---|---|---|---|---|\n",
                option
                    .as_deref()
                    .map_or("Default (no detected version or out of range)".to_string(), |r| {
                        format!("Version `{r}`")
                    })
            ));
            for platform in Platform::ALL {
                let rows: Vec<&Materialized> = materialized
                    .iter()
                    .filter(|m| m.platform == platform && m.version_range == option)
                    .collect();
                let mut intents: Vec<Option<String>> = Vec::new();
                for m in &rows {
                    if !intents.contains(&m.intent) {
                        intents.push(m.intent.clone());
                    }
                }
                for intent in intents {
                    let per_arch: Vec<(&Materialized, [String; 5])> = Architecture::ALL
                        .iter()
                        .filter_map(|arch| {
                            rows.iter()
                                .find(|m| m.architecture == *arch && m.intent == intent)
                        })
                        .map(|m| (*m, row_cells(m)))
                        .collect();
                    let same = per_arch.windows(2).all(|w| w[0].1 == w[1].1)
                        && per_arch.len() == Architecture::ALL.len();
                    let shown: Vec<(String, &[String; 5])> = if same {
                        vec![("any".to_string(), &per_arch[0].1)]
                    } else {
                        per_arch
                            .iter()
                            .map(|(m, c)| (m.architecture.to_string(), c))
                            .collect()
                    };
                    for (arch, cells) in shown {
                        out.push_str(&format!(
                            "| {platform} | {arch} | {} | {} |\n",
                            intent.as_deref().unwrap_or("(all)"),
                            cells.join(" | ")
                        ));
                    }
                }
            }
        }
    }
    Ok(out)
}
