#!/usr/bin/env node
// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

// Regenerates conformance/vectors/*.json from the TypeScript reference
// implementation (run `npm run build` first). The Rust and C# bindings test
// their path normalization and canonical JSON against these files, so the
// three languages cannot drift apart silently.
//
//   npm run build && node scripts/generate-vectors.mjs
//
// Non-ASCII inputs are written with \u escapes so this file stays ASCII.
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { isAbsolutePath, normalizePath, pathKeySegments } from '../dist/catalog.js';
import { canonicalJson, canonicalSha256 } from '../dist/canonical-json.js';

const out = name => fileURLToPath(new URL(`../conformance/vectors/${name}`, import.meta.url));

const windows = [
  'C:\\Tools', 'c:\\tools\\', 'C:\\a\\.\\b\\..\\c', 'C:/a//b/', 'C:\\', 'C:\\\\', 'C:\\..\\x',
  '\\\\server\\share\\x\\', '\\\\server\\share', 'D:\\src', 'C:\\Program Files\\Git\\cmd',
  'C:\\a\\..\\..\\b', 'C:\\x\\y\\.', '/usr/bin', '\\rooted\\', 'C:\\\u00c9t\u00e9', 'C:rel', 'rel\\x', '',
];
const posix = ['/usr/bin', '/usr//bin/', '/a/./b/../c', '/', '//', '///x', '/Users/dev/app/', '/a/../../b', '/x/y/.', '/Tools', '/..', '/\u00c9t\u00e9', 'rel/x', './x', ''];
const row = (input, platform) => ({
  input,
  absolute: isAbsolutePath(input, platform),
  normalized: input !== '' && isAbsolutePath(input, platform) ? normalizePath(input, platform) : null,
  keySegments: pathKeySegments(input, platform),
});
writeFileSync(out('paths.json'), `${JSON.stringify({
  $comment: 'Generated by scripts/generate-vectors.mjs. Path rules every binding reproduces exactly: Node path.win32/path.posix isAbsolute and normalize, then trailing-separator removal unless only the root remains. keySegments applies the per-OS casing rule (fold on windows and macos). normalized is null for a relative input; the resolver rejects those before normalizing.',
  windows: windows.map(v => row(v, 'windows')),
  linux: posix.map(v => row(v, 'linux')),
  macos: posix.map(v => row(v, 'macos')),
}, null, 2)}\n`);

// Each case is raw JSON text so a parser sees the original tokens.
const texts = [
  '{"b":1,"a":[3,2,{"d":null,"c":true}]}',
  '{"\\u00e9":1,"z":2,"Z":3,"\\ue000":4,"\\ud83d\\ude00":5,"":6}',
  '["tab\\t","nl\\n","q\\"","bs\\\\","ctl\\u0001\\u001f\\u007f","uni \\u00e9 \\ud83d\\ude00","/","\\u2028"]',
  '[0,-0,1,1.0,-1,1.5,0.1,1e21,1e-7,123456789012345680000,12345678901234567890,5e-324,1.7976931348623157e308,100,1e20,0.000001,2.5e-7,-1234.5678,1E2,-0.0,0.30000000000000004]',
  '{"nested":{"k":[],"o":{}}}',
  '"plain"',
  '42',
  'false',
  'null',
];
writeFileSync(out('canonical-json.json'), `${JSON.stringify({
  $comment: 'Generated by scripts/generate-vectors.mjs. Canonical JSON: object keys sorted by UTF-16 code units, arrays in order, no whitespace, JSON.stringify string escaping, and ECMAScript Number::toString for every number. sha256 is lower-case hex over the UTF-8 canonical text. Parse `json`, canonicalize, and compare both fields.',
  cases: texts.map(json => ({ json, canonical: canonicalJson(JSON.parse(json)), sha256: canonicalSha256(JSON.parse(json)) })),
}, null, 2)}\n`);
console.log('wrote conformance/vectors/paths.json and conformance/vectors/canonical-json.json');
